### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by MB-Mtl** [baumgach/acdc_segmenter#3]
Great project. Were you planning on supplying some pre-trained weights?

**Comment by baumgach** [comment]
Hello, I finally got around to retraining all of the models. Unfortunately, I realised that uploading all the models to github is not possible due to the file size limit. I made the weights of the best performing experiment in the paper available here: https://git.ee.ethz.ch/baumgach/acdc_pretrained_weights 

I am happy to email you a link any other pretrained models you need. Just let me know which ones you need via email. Best wishes, Christian
